import type {
    RiskRegisterItem,
    ScorecardGate,
    SmokeJourney,
} from '@/lib/platform/types';

export const SMOKE_JOURNEY_BASELINE: Omit<SmokeJourney, 'status'>[] = [
    {
        key: 'auth_mfa',
        title: 'Auth + MFA',
        actors: ['anonimo', 'trucker', 'business owner', 'admin plataforma'],
        automation: 'hybrid',
        evidence_path: '/SPTRINTS/90_QA_MATRIX.md',
        notes: 'Validar alta, login, MFA setup, MFA verify y acceso AAL2.',
    },
    {
        key: 'trip_money',
        title: 'Offer -> pay -> webhook -> trip',
        actors: ['business owner', 'trucker'],
        automation: 'manual',
        evidence_path: '/SPTRINTS/90_QA_MATRIX.md',
        notes: 'Debe terminar con pago completado, webhook aplicado y viaje trazable.',
    },
    {
        key: 'wallet_withdrawal',
        title: 'Wallet -> withdrawal',
        actors: ['trucker', 'finance admin', 'admin plataforma'],
        automation: 'manual',
        evidence_path: '/SPTRINTS/90_QA_MATRIX.md',
        notes: 'Validar hold, aprobacion o rechazo, reversal y before/after del ledger.',
    },
    {
        key: 'advance_cycle',
        title: 'Advance request -> approval -> repayment',
        actors: ['trucker', 'finance admin', 'ops admin'],
        automation: 'manual',
        evidence_path: '/SPTRINTS/90_QA_MATRIX.md',
        notes: 'Validar policy snapshot, exposure snapshot, desembolso y repayment waterfall.',
    },
    {
        key: 'warehouse_ops',
        title: 'Warehouse appointment -> receipt/dispatch -> incident',
        actors: ['business owner', 'operator', 'auditor'],
        automation: 'manual',
        evidence_path: '/SPTRINTS/90_QA_MATRIX.md',
        notes: 'Validar cita, recepcion o despacho, incidente y cierre.',
    },
    {
        key: 'holding_admin',
        title: 'Holding approval -> admin reconcile',
        actors: ['holding owner', 'finance admin', 'analyst', 'admin plataforma'],
        automation: 'manual',
        evidence_path: '/SPTRINTS/90_QA_MATRIX.md',
        notes: 'Validar approval, SLA, requestId y reconcile administrativo.',
    },
];

export const RISK_REGISTER_BASELINE: RiskRegisterItem[] = [
    {
        key: 'focus_too_wide',
        category: 'strategic',
        risk: 'Foco demasiado ancho antes de repeticion real.',
        owner: 'CEO / Founder',
        early_signal: 'Se reabren mercados o frentes nuevos sin clientes pagos repetibles.',
        mitigation: 'Mantener CO como unico mercado abierto y usar gates para decidir expansion.',
        status: 'open',
        review_cadence: 'weekly',
        blocker: true,
    },
    {
        key: 'vision_without_product',
        category: 'strategic',
        risk: 'La narrativa comercial promete mas que el producto operable.',
        owner: 'CEO / Founder',
        early_signal: 'Playbooks o pricing venden flujos que aun requieren manejo oculto.',
        mitigation: 'Alinear homepage, pricing y soporte al producto que corre hoy.',
        status: 'partial',
        review_cadence: 'weekly',
        blocker: true,
    },
    {
        key: 'smoke_evidence_gap',
        category: 'technical',
        risk: 'No existe evidencia ejecutada de la smoke suite critica.',
        owner: 'CTO / Founding Engineer',
        early_signal: 'SPTRINTS/90 sigue con journeys en pendiente.',
        mitigation: 'Ejecutar smoke suite y adjuntar evidencia por journey.',
        status: 'open',
        review_cadence: 'weekly',
        blocker: true,
    },
    {
        key: 'lint_warning_backlog',
        category: 'technical',
        risk: 'Backlog de lint warnings en dominios sensibles.',
        owner: 'CTO / Founding Engineer',
        early_signal: 'lint-report.json conserva warnings en auth, payments, wallet, admin o holding.',
        mitigation: 'Triage por dominio y limpieza progresiva antes de release financiero serio.',
        status: 'partial',
        review_cadence: 'weekly',
        blocker: false,
    },
    {
        key: 'api_contract_debt',
        category: 'technical',
        risk: 'Algunas rutas legacy pueden degradar consistencia de contratos.',
        owner: 'CTO / Founding Engineer',
        early_signal: 'Responses sin envelope o sin requestId en dominios criticos.',
        mitigation: 'Mantener envelope oficial y revisar endpoints legacy.',
        status: 'partial',
        review_cadence: 'biweekly',
        blocker: false,
    },
    {
        key: 'colombia_first_ui',
        category: 'expansion',
        risk: 'Persisten superficies visuales parcialmente Colombia-first.',
        owner: 'Head of Ops',
        early_signal: 'Formularios o labels siguen asumiendo CO fuera de flags.',
        mitigation: 'Lanzar solo CO y mantener PE/EC cerrados hasta cerrar surfaces pendientes.',
        status: 'partial',
        review_cadence: 'biweekly',
        blocker: false,
    },
    {
        key: 'settlement_traceability',
        category: 'financial',
        risk: 'Settlement ambiguo o no explicable.',
        owner: 'Finance Lead',
        early_signal: 'Diferencias entre payments, transactions y admin overview.',
        mitigation: 'Mantener ledger canonico y revisar trip_pending -> trip_deposit.',
        status: 'mitigated',
        review_cadence: 'weekly',
        blocker: true,
    },
    {
        key: 'treasury_caps',
        category: 'financial',
        risk: 'Caps de treasury o policy mal aplicados.',
        owner: 'Finance Lead',
        early_signal: 'Adelantos aprobados fuera de exposure o treasury.',
        mitigation: 'Revisar exposure snapshot y portfolio metrics semanalmente.',
        status: 'mitigated',
        review_cadence: 'weekly',
        blocker: true,
    },
    {
        key: 'delinquency_control',
        category: 'financial',
        risk: 'Mora temprana sin accion de cobranza.',
        owner: 'Finance Lead',
        early_signal: 'PAR7 o PAR30 crecen sin follow-up.',
        mitigation: 'Seguimiento semanal de cohorts y collections.',
        status: 'partial',
        review_cadence: 'weekly',
        blocker: true,
    },
    {
        key: 'partner_compliance_gap',
        category: 'financial',
        risk: 'Partners y compliance por pais no estan cerrados.',
        owner: 'CEO / Founder',
        early_signal: 'PE/EC aparecen abiertos sin counterparties reales ni counsel local.',
        mitigation: 'Dejar PE/EC en not open hasta cerrar partner y compliance.',
        status: 'open',
        review_cadence: 'weekly',
        blocker: true,
    },
    {
        key: 'onboarding_cost',
        category: 'commercial',
        risk: 'Implementacion asistida demasiado costosa para repetirse.',
        owner: 'Growth Lead',
        early_signal: 'Tiempo a primer valor crece o depende del fundador.',
        mitigation: 'Usar checklist, playbooks y support roster como proceso repetible.',
        status: 'partial',
        review_cadence: 'weekly',
        blocker: false,
    },
    {
        key: 'activation_conversion',
        category: 'commercial',
        risk: 'Las activaciones iniciales no convierten a pago real.',
        owner: 'CEO / Founder',
        early_signal: 'Muchas conversaciones calificadas no terminan en contrato o uso real.',
        mitigation: 'Scorecard mensual y decision de foco por gate.',
        status: 'open',
        review_cadence: 'weekly',
        blocker: true,
    },
    {
        key: 'support_founder_dependency',
        category: 'operational',
        risk: 'El soporte sigue dependiendo del fundador.',
        owner: 'Support Lead',
        early_signal: 'Incidentes criticos terminan en canales informales.',
        mitigation: 'Usar support-escalation y admin como fuente unica de trabajo.',
        status: 'partial',
        review_cadence: 'weekly',
        blocker: true,
    },
    {
        key: 'rollback_gap',
        category: 'operational',
        risk: 'No existe rollback practicado para release.',
        owner: 'CTO / Founding Engineer',
        early_signal: 'No se ha rehecho la decision tree de rollback antes del launch.',
        mitigation: 'Mantener runbook de rollback y ejecutar rehearsal previo.',
        status: 'partial',
        review_cadence: 'weekly',
        blocker: true,
    },
    {
        key: 'observability_runbooks',
        category: 'operational',
        risk: 'Incidentes sin requestId o sin runbook accionable.',
        owner: 'Support Lead',
        early_signal: 'Incidentes no reproducibles o sin replay seguro.',
        mitigation: 'Mantener operation events, incidents y runbooks activos.',
        status: 'mitigated',
        review_cadence: 'weekly',
        blocker: false,
    },
];

export const SCORECARD_GATES_BASELINE: Omit<ScorecardGate, 'status' | 'evidence_basis'>[] = [
    {
        key: 'gate_1',
        title: 'Gate 1 - Fundacion',
        sprint_range: '01-05',
        criteria: [
            'Repo y release path claros',
            'Build verde y deuda critica controlada',
            'Auth sensible endurecida',
            'Contratos API unificados en dominios criticos',
            'Mapa legal/financiero definido',
        ],
        action_if_failed: [
            'No escalar lending todavia',
            'No abrir nuevos mercados',
        ],
    },
    {
        key: 'gate_2',
        title: 'Gate 2 - Dinero y operacion',
        sprint_range: '06-10',
        criteria: [
            '1 cliente operativo pago o comprometido',
            '1 flujo pago -> viaje -> settlement funcionando',
            '1 wallet ledger explicable end-to-end',
            '1 ciclo de advance con repayment visible',
            'Mora temprana bajo control',
        ],
        action_if_failed: [
            'Estrechar foco a Logistics OS + payments',
            'Pausar expansion del libro de credito',
        ],
    },
    {
        key: 'gate_3',
        title: 'Gate 3 - Enterprise y venta',
        sprint_range: '11-13',
        criteria: [
            '3 clientes pagos o 2 enterprise con uso real',
            'Recorrido comercial de 15 minutos sin improvisacion',
            'Onboarding repetible',
            'Una empresa multiunidad operando en la consola',
        ],
        action_if_failed: [
            'Reducir complejidad enterprise',
            'Simplificar pricing y motion comercial',
        ],
    },
    {
        key: 'gate_4',
        title: 'Gate 4 - Expansion y reliability',
        sprint_range: '14-15',
        criteria: [
            'Core desacoplado de Colombia',
            'Reliability minima probada',
            'Decision clara de expansion o consolidacion local',
        ],
        action_if_failed: [
            'Mantener CO como mercado unico abierto',
            'No abrir PE/EC comercialmente',
        ],
    },
];
