import {
    BarChart3,
    Bell,
    Building2,
    CalendarClock,
    ClipboardCheck,
    Crown,
    DollarSign,
    FileText,
    HelpCircle,
    Home,
    Package,
    PlusCircle,
    Search,
    Settings,
    ShieldCheck,
    Truck,
    User,
    Users,
    Warehouse,
    TrendingDown,
} from 'lucide-react';
import type { NavItem, SidebarNavCounts, SidebarSectionKey, SidebarSectionMeta, SidebarUserType } from './types';

export const SIDEBAR_STATE_KEY = 'kargax-sidebar-collapsed';
export const SIDEBAR_EXPANDED_WIDTH = 304;
export const SIDEBAR_COLLAPSED_WIDTH = 88;

export const SIDEBAR_SECTION_ORDER: SidebarSectionKey[] = [
    'command',
    'operations',
    'marketplace',
    'money',
    'governance',
];

export const SIDEBAR_SECTION_META: Record<SidebarSectionKey, SidebarSectionMeta> = {
    command: {
        title: 'Centro de mando',
        description: 'Resumen ejecutivo de tu operacion.',
        collapsedLabel: 'Mando',
    },
    operations: {
        title: 'Operacion privada',
        description: 'Bodegas, flota y equipo propio.',
        collapsedLabel: 'Operacion',
    },
    marketplace: {
        title: 'Marketplace',
        description: 'Capacidad externa sin perder trazabilidad.',
        collapsedLabel: 'MK',
    },
    money: {
        title: 'Dinero y limites',
        description: 'Saldo operativo, planes y control de uso.',
        collapsedLabel: '$',
    },
    governance: {
        title: 'Gobierno',
        description: 'Empresa, auditoria y administracion.',
        collapsedLabel: 'Gov',
    },
    support: {
        title: 'Cuenta',
        description: 'Perfil, ayuda y preferencias.',
        collapsedLabel: 'Cuenta',
    },
};

export function getNavigationItems(
    userType: SidebarUserType,
    counts?: SidebarNavCounts,
    canAccessCeo = false
): NavItem[] {
    return [
        {
            id: 'home',
            labelKey: 'nav.home',
            fallbackLabel: 'Inicio',
            icon: Home,
            href: '/dashboard',
            section: 'command',
            description: 'Resumen ejecutivo de tu operacion.',
            priority: 'primary',
            allowedUserTypes: ['trucker', 'business', 'admin'],
        },
        {
            id: 'warehouses',
            labelKey: 'nav.warehouses',
            fallbackLabel: 'Bodegas',
            icon: Warehouse,
            href: '/bodegas',
            section: 'operations',
            description: 'Inventario, picking y despacho.',
            allowedUserTypes: ['business', 'admin'],
        },
        {
            id: 'team',
            labelKey: 'nav.team',
            fallbackLabel: 'Equipo',
            icon: Users,
            href: '/equipo',
            section: 'operations',
            description: 'Usuarios internos y roles operativos.',
            allowedUserTypes: ['business', 'admin'],
        },
        {
            id: 'private-fleet',
            labelKey: 'nav.privateFleet',
            fallbackLabel: 'Flota privada',
            icon: Truck,
            href: '/dashboard/flota',
            section: 'operations',
            description: 'Conductores propios y compensacion.',
            allowedUserTypes: ['trucker', 'business', 'admin'],
        },
        {
            id: 'business-intelligence',
            labelKey: 'nav.businessIntelligence',
            fallbackLabel: 'Inteligencia',
            icon: BarChart3,
            href: '/dashboard/inteligencia',
            section: 'operations',
            description: 'Indicadores para decidir sin Excel.',
            allowedUserTypes: ['business', 'admin'],
        },
        {
            id: 'margin-control',
            labelKey: 'nav.marginControl',
            fallbackLabel: 'Control de margen',
            icon: TrendingDown,
            href: '/dashboard/control-margen',
            section: 'operations',
            description: 'Costo, margen y rentabilidad por ruta.',
            allowedUserTypes: ['business', 'admin'],
        },
        {
            id: 'offers-browse',
            labelKey: 'nav.browseOffers',
            fallbackLabel: userType === 'trucker' ? 'Cargas disponibles' : 'Explorar marketplace',
            icon: Search,
            href: '/ofertas',
            section: 'marketplace',
            description: 'Ofertas externas separadas de tu operacion.',
            allowedUserTypes: ['trucker', 'business', 'admin'],
        },
        {
            id: 'offers-publish',
            labelKey: 'nav.publishOffer',
            fallbackLabel: 'Publicar en marketplace',
            icon: PlusCircle,
            href: '/ofertas/publicar',
            section: 'marketplace',
            description: 'Abrir capacidad externa con trazabilidad.',
            allowedUserTypes: ['business', 'admin'],
        },
        {
            id: 'my-offers',
            labelKey: 'nav.myOffers',
            fallbackLabel: 'Ofertas publicadas',
            icon: Package,
            href: '/ofertas/mis-ofertas',
            section: 'marketplace',
            description: 'Gestiona cargas abiertas.',
            allowedUserTypes: ['business', 'admin'],
        },
        {
            id: 'pod-marketplace',
            labelKey: 'nav.podMarketplace',
            fallbackLabel: 'Evidencia marketplace',
            icon: ClipboardCheck,
            href: '/pod-marketplace',
            section: 'marketplace',
            description: 'POD digital de rutas externas.',
            allowedUserTypes: ['business', 'admin'],
        },
        {
            id: 'received-applications',
            labelKey: 'nav.receivedApplications',
            fallbackLabel: 'Postulaciones marketplace',
            icon: Users,
            href: '/postulaciones-recibidas',
            section: 'marketplace',
            badge: counts?.applications || undefined,
            description: 'Transportadores interesados en tus cargas.',
            allowedUserTypes: ['business', 'admin'],
        },
        {
            id: 'my-applications',
            labelKey: 'nav.myApplications',
            fallbackLabel: 'Mis postulaciones',
            icon: FileText,
            href: '/postulaciones',
            section: 'marketplace',
            badge: counts?.applicationUpdates || undefined,
            description: 'Seguimiento de cargas solicitadas.',
            allowedUserTypes: ['trucker'],
        },
        {
            id: 'assigned-trips',
            labelKey: 'nav.assignedTrips',
            fallbackLabel: 'Viajes asignados',
            icon: Truck,
            href: '/viajes-asignados',
            section: 'operations',
            badge: counts?.acceptedJobs || undefined,
            description: 'Trabajo activo con evidencia y PIN.',
            allowedUserTypes: ['trucker'],
        },
        {
            id: 'wallet',
            labelKey: 'nav.wallet',
            fallbackLabel: 'Billetera operativa',
            icon: DollarSign,
            href: '/billetera',
            section: 'money',
            description: 'Liquidaciones y retiros operativos.',
            allowedUserTypes: ['trucker'],
        },
        {
            id: 'plans',
            labelKey: 'nav.plans',
            fallbackLabel: 'Planes y limites',
            icon: DollarSign,
            href: '/planes',
            section: 'money',
            description: 'Capacidad contratada y upgrade.',
            allowedUserTypes: ['business', 'admin'],
        },
        {
            id: 'corporate',
            labelKey: 'nav.corporate',
            fallbackLabel: 'Corporativo',
            icon: Building2,
            href: '/corporativo',
            section: 'governance',
            description: 'Holding, sedes y control superior.',
            allowedUserTypes: ['business', 'admin'],
        },
        {
            id: 'notifications',
            labelKey: 'nav.notifications',
            fallbackLabel: 'Notificaciones',
            icon: Bell,
            href: '/notificaciones',
            section: 'governance',
            badge: counts?.total || undefined,
            description: 'Alertas operativas y cambios de estado.',
            allowedUserTypes: ['trucker', 'business', 'admin'],
        },
        {
            id: 'admin',
            labelKey: 'nav.admin',
            fallbackLabel: 'Admin',
            icon: ShieldCheck,
            href: '/admin',
            section: 'governance',
            description: 'Control interno KargaX.',
            allowedUserTypes: ['admin'],
        },
        ...(canAccessCeo
            ? [
                {
                    id: 'admin-ceo',
                    labelKey: 'nav.ceo',
                    fallbackLabel: 'CEO KargaX',
                    icon: Crown,
                    href: '/admin/ceo',
                    section: 'governance' as const,
                    description: 'Sala ejecutiva de decisiones.',
                    priority: 'primary' as const,
                    allowedUserTypes: ['admin'] as SidebarUserType[],
                },
            ]
            : []),
    ];
}

export function getSecondaryNavItems(): NavItem[] {
    return [
        {
            id: 'profile',
            labelKey: 'nav.profile',
            fallbackLabel: 'Mi Perfil',
            icon: User,
            href: '/perfil',
            section: 'support',
        },
        {
            id: 'settings',
            labelKey: 'nav.settings',
            fallbackLabel: 'Configuracion',
            icon: Settings,
            href: '/configuracion',
            section: 'support',
        },
        {
            id: 'help',
            labelKey: 'nav.help',
            fallbackLabel: 'Ayuda',
            icon: HelpCircle,
            href: '/ayuda',
            section: 'support',
        },
    ];
}

export function getWarehouseScopedNavigation(warehouseId: string, counts?: Pick<SidebarNavCounts, 'total'>): NavItem[] {
    return [
        {
            id: 'warehouse-overview',
            labelKey: 'nav.warehouseOverview',
            fallbackLabel: 'Resumen',
            icon: Home,
            href: `/bodegas/${warehouseId}`,
            section: 'command',
            description: 'Estado de la bodega activa.',
            allowedUserTypes: ['business'],
        },
        {
            id: 'warehouse-appointments',
            labelKey: 'nav.warehouseAppointments',
            fallbackLabel: 'Citas',
            icon: CalendarClock,
            href: `/bodegas/${warehouseId}/citas`,
            section: 'operations',
            description: 'Agenda de ingresos y salidas.',
            allowedUserTypes: ['business'],
        },
        {
            id: 'warehouse-docks',
            labelKey: 'nav.warehouseDocks',
            fallbackLabel: 'Muelles',
            icon: Warehouse,
            href: `/bodegas/${warehouseId}/muelles`,
            section: 'operations',
            description: 'Capacidad fisica disponible.',
            allowedUserTypes: ['business'],
        },
        {
            id: 'warehouse-inventory',
            labelKey: 'nav.warehouseInventory',
            fallbackLabel: 'Inventario',
            icon: Package,
            href: `/bodegas/${warehouseId}/inventario`,
            section: 'operations',
            description: 'Existencias y ubicaciones.',
            allowedUserTypes: ['business'],
        },
        {
            id: 'warehouse-receipts',
            labelKey: 'nav.warehouseReceipts',
            fallbackLabel: 'Recepciones',
            icon: ClipboardCheck,
            href: `/bodegas/${warehouseId}/recepciones`,
            section: 'operations',
            description: 'Entradas con control operativo.',
            allowedUserTypes: ['business'],
        },
        {
            id: 'warehouse-picking',
            labelKey: 'nav.warehousePicking',
            fallbackLabel: 'Picking',
            icon: FileText,
            href: `/bodegas/${warehouseId}/picking`,
            section: 'operations',
            description: 'Preparacion de pedidos.',
            allowedUserTypes: ['business'],
        },
        {
            id: 'warehouse-dispatches',
            labelKey: 'nav.warehouseDispatches',
            fallbackLabel: 'Despachos',
            icon: Truck,
            href: `/bodegas/${warehouseId}/despachos`,
            section: 'operations',
            description: 'Salida y cierre logistico.',
            allowedUserTypes: ['business'],
        },
        {
            id: 'warehouse-incidents',
            labelKey: 'nav.warehouseIncidents',
            fallbackLabel: 'Incidentes',
            icon: Bell,
            href: `/bodegas/${warehouseId}/incidentes`,
            section: 'operations',
            description: 'Novedades con trazabilidad.',
            allowedUserTypes: ['business'],
        },
        {
            id: 'warehouse-analytics',
            labelKey: 'nav.warehouseAnalytics',
            fallbackLabel: 'Analitica',
            icon: BarChart3,
            href: `/bodegas/${warehouseId}/analitica`,
            section: 'operations',
            description: 'Indicadores de bodega.',
            allowedUserTypes: ['business'],
        },
        {
            id: 'margin-control',
            labelKey: 'nav.marginControl',
            fallbackLabel: 'Control de margen',
            icon: TrendingDown,
            href: '/dashboard/control-margen',
            section: 'money',
            description: 'Rentabilidad de la operacion.',
            allowedUserTypes: ['business'],
        },
        {
            id: 'notifications',
            labelKey: 'nav.notifications',
            fallbackLabel: 'Notificaciones',
            icon: Bell,
            href: '/notificaciones',
            section: 'governance',
            badge: counts?.total || undefined,
            description: 'Alertas de la bodega activa.',
            allowedUserTypes: ['business'],
        },
    ];
}
