// =============================================================================
// Perú - 26 Departamentos/Regiones + Ciudades principales COMPLETO
// =============================================================================
import type { Subdivision, City } from './index';

export const PE_SUBDIVISIONS: readonly Subdivision[] = [
  { code: 'PE-AMA', name: 'Amazonas', capital: 'Chachapoyas', country: 'PE' },
  { code: 'PE-ANC', name: 'Áncash', capital: 'Huaraz', country: 'PE' },
  { code: 'PE-APU', name: 'Apurímac', capital: 'Abancay', country: 'PE' },
  { code: 'PE-ARE', name: 'Arequipa', capital: 'Arequipa', country: 'PE' },
  { code: 'PE-AYA', name: 'Ayacucho', capital: 'Ayacucho', country: 'PE' },
  { code: 'PE-CAJ', name: 'Cajamarca', capital: 'Cajamarca', country: 'PE' },
  { code: 'PE-CAL', name: 'Callao', capital: 'Callao', country: 'PE' },
  { code: 'PE-CUS', name: 'Cusco', capital: 'Cusco', country: 'PE' },
  { code: 'PE-HUV', name: 'Huancavelica', capital: 'Huancavelica', country: 'PE' },
  { code: 'PE-HUC', name: 'Huánuco', capital: 'Huánuco', country: 'PE' },
  { code: 'PE-ICA', name: 'Ica', capital: 'Ica', country: 'PE' },
  { code: 'PE-JUN', name: 'Junín', capital: 'Huancayo', country: 'PE' },
  { code: 'PE-LAL', name: 'La Libertad', capital: 'Trujillo', country: 'PE' },
  { code: 'PE-LAM', name: 'Lambayeque', capital: 'Chiclayo', country: 'PE' },
  { code: 'PE-LIM', name: 'Lima', capital: 'Lima', country: 'PE' },
  { code: 'PE-LOR', name: 'Loreto', capital: 'Iquitos', country: 'PE' },
  { code: 'PE-MDD', name: 'Madre de Dios', capital: 'Puerto Maldonado', country: 'PE' },
  { code: 'PE-MOQ', name: 'Moquegua', capital: 'Moquegua', country: 'PE' },
  { code: 'PE-PAS', name: 'Pasco', capital: 'Cerro de Pasco', country: 'PE' },
  { code: 'PE-PIU', name: 'Piura', capital: 'Piura', country: 'PE' },
  { code: 'PE-PUN', name: 'Puno', capital: 'Puno', country: 'PE' },
  { code: 'PE-SAM', name: 'San Martín', capital: 'Moyobamba', country: 'PE' },
  { code: 'PE-TAC', name: 'Tacna', capital: 'Tacna', country: 'PE' },
  { code: 'PE-TUM', name: 'Tumbes', capital: 'Tumbes', country: 'PE' },
  { code: 'PE-UCA', name: 'Ucayali', capital: 'Pucallpa', country: 'PE' },
];

export const PE_CITIES: readonly City[] = [
  { code: 'PE-CHP', name: 'Chachapoyas', subdivisionCode: 'PE-AMA', country: 'PE', isCapital: true },
  { code: 'PE-BAG', name: 'Bagua', subdivisionCode: 'PE-AMA', country: 'PE' },
  { code: 'PE-HRZ', name: 'Huaraz', subdivisionCode: 'PE-ANC', country: 'PE', isCapital: true },
  { code: 'PE-CHM', name: 'Chimbote', subdivisionCode: 'PE-ANC', country: 'PE' },
  { code: 'PE-CRZ', name: 'Caraz', subdivisionCode: 'PE-ANC', country: 'PE' },
  { code: 'PE-ABC', name: 'Abancay', subdivisionCode: 'PE-APU', country: 'PE', isCapital: true },
  { code: 'PE-AND', name: 'Andahuaylas', subdivisionCode: 'PE-APU', country: 'PE' },
  { code: 'PE-AQP', name: 'Arequipa', subdivisionCode: 'PE-ARE', country: 'PE', isCapital: true },
  { code: 'PE-MOL', name: 'Mollendo', subdivisionCode: 'PE-ARE', country: 'PE' },
  { code: 'PE-CAM', name: 'Camaná', subdivisionCode: 'PE-ARE', country: 'PE' },
  { code: 'PE-AYC', name: 'Ayacucho', subdivisionCode: 'PE-AYA', country: 'PE', isCapital: true },
  { code: 'PE-HNT', name: 'Huanta', subdivisionCode: 'PE-AYA', country: 'PE' },
  { code: 'PE-CJM', name: 'Cajamarca', subdivisionCode: 'PE-CAJ', country: 'PE', isCapital: true },
  { code: 'PE-JAE', name: 'Jaén', subdivisionCode: 'PE-CAJ', country: 'PE' },
  { code: 'PE-CLO', name: 'Callao', subdivisionCode: 'PE-CAL', country: 'PE', isCapital: true },
  { code: 'PE-BEL', name: 'Bellavista', subdivisionCode: 'PE-CAL', country: 'PE' },
  { code: 'PE-CUZ', name: 'Cusco', subdivisionCode: 'PE-CUS', country: 'PE', isCapital: true },
  { code: 'PE-SIC', name: 'Sicuani', subdivisionCode: 'PE-CUS', country: 'PE' },
  { code: 'PE-QUI', name: 'Quillabamba', subdivisionCode: 'PE-CUS', country: 'PE' },
  { code: 'PE-HVC', name: 'Huancavelica', subdivisionCode: 'PE-HUV', country: 'PE', isCapital: true },
  { code: 'PE-HNQ', name: 'Huánuco', subdivisionCode: 'PE-HUC', country: 'PE', isCapital: true },
  { code: 'PE-TMA', name: 'Tingo María', subdivisionCode: 'PE-HUC', country: 'PE' },
  { code: 'PE-ICA', name: 'Ica', subdivisionCode: 'PE-ICA', country: 'PE', isCapital: true },
  { code: 'PE-NZC', name: 'Nazca', subdivisionCode: 'PE-ICA', country: 'PE' },
  { code: 'PE-PSC', name: 'Pisco', subdivisionCode: 'PE-ICA', country: 'PE' },
  { code: 'PE-CHC', name: 'Chincha Alta', subdivisionCode: 'PE-ICA', country: 'PE' },
  { code: 'PE-HYO', name: 'Huancayo', subdivisionCode: 'PE-JUN', country: 'PE', isCapital: true },
  { code: 'PE-TAR', name: 'Tarma', subdivisionCode: 'PE-JUN', country: 'PE' },
  { code: 'PE-MRC', name: 'La Merced', subdivisionCode: 'PE-JUN', country: 'PE' },
  { code: 'PE-TRU', name: 'Trujillo', subdivisionCode: 'PE-LAL', country: 'PE', isCapital: true },
  { code: 'PE-PCC', name: 'Pacasmayo', subdivisionCode: 'PE-LAL', country: 'PE' },
  { code: 'PE-CHY', name: 'Chiclayo', subdivisionCode: 'PE-LAM', country: 'PE', isCapital: true },
  { code: 'PE-LMB', name: 'Lambayeque', subdivisionCode: 'PE-LAM', country: 'PE' },
  { code: 'PE-FRN', name: 'Ferreñafe', subdivisionCode: 'PE-LAM', country: 'PE' },
  { code: 'PE-LMA', name: 'Lima', subdivisionCode: 'PE-LIM', country: 'PE', isCapital: true },
  { code: 'PE-HCH', name: 'Huacho', subdivisionCode: 'PE-LIM', country: 'PE' },
  { code: 'PE-CNT', name: 'Cañete', subdivisionCode: 'PE-LIM', country: 'PE' },
  { code: 'PE-HRL', name: 'Huaral', subdivisionCode: 'PE-LIM', country: 'PE' },
  { code: 'PE-IQT', name: 'Iquitos', subdivisionCode: 'PE-LOR', country: 'PE', isCapital: true },
  { code: 'PE-YRM', name: 'Yurimaguas', subdivisionCode: 'PE-LOR', country: 'PE' },
  { code: 'PE-PML', name: 'Puerto Maldonado', subdivisionCode: 'PE-MDD', country: 'PE', isCapital: true },
  { code: 'PE-MQG', name: 'Moquegua', subdivisionCode: 'PE-MOQ', country: 'PE', isCapital: true },
  { code: 'PE-ILO', name: 'Ilo', subdivisionCode: 'PE-MOQ', country: 'PE' },
  { code: 'PE-CDP', name: 'Cerro de Pasco', subdivisionCode: 'PE-PAS', country: 'PE', isCapital: true },
  { code: 'PE-PIR', name: 'Piura', subdivisionCode: 'PE-PIU', country: 'PE', isCapital: true },
  { code: 'PE-SUL', name: 'Sullana', subdivisionCode: 'PE-PIU', country: 'PE' },
  { code: 'PE-TLR', name: 'Talara', subdivisionCode: 'PE-PIU', country: 'PE' },
  { code: 'PE-PIT', name: 'Paita', subdivisionCode: 'PE-PIU', country: 'PE' },
  { code: 'PE-PNO', name: 'Puno', subdivisionCode: 'PE-PUN', country: 'PE', isCapital: true },
  { code: 'PE-JUL', name: 'Juliaca', subdivisionCode: 'PE-PUN', country: 'PE' },
  { code: 'PE-AYV', name: 'Ayaviri', subdivisionCode: 'PE-PUN', country: 'PE' },
  { code: 'PE-MYB', name: 'Moyobamba', subdivisionCode: 'PE-SAM', country: 'PE', isCapital: true },
  { code: 'PE-TRP', name: 'Tarapoto', subdivisionCode: 'PE-SAM', country: 'PE' },
  { code: 'PE-TCN', name: 'Tacna', subdivisionCode: 'PE-TAC', country: 'PE', isCapital: true },
  { code: 'PE-TMB', name: 'Tumbes', subdivisionCode: 'PE-TUM', country: 'PE', isCapital: true },
  { code: 'PE-ZRL', name: 'Zarumilla', subdivisionCode: 'PE-TUM', country: 'PE' },
  { code: 'PE-PCL', name: 'Pucallpa', subdivisionCode: 'PE-UCA', country: 'PE', isCapital: true },
  { code: 'PE-AGY', name: 'Aguaytía', subdivisionCode: 'PE-UCA', country: 'PE' },
];
