// =============================================================================
// Ecuador - 24 Provincias + Ciudades principales COMPLETO
// =============================================================================
import type { Subdivision, City } from './index';

export const EC_SUBDIVISIONS: readonly Subdivision[] = [
  { code: 'EC-A', name: 'Azuay', capital: 'Cuenca', country: 'EC' },
  { code: 'EC-B', name: 'Bolívar', capital: 'Guaranda', country: 'EC' },
  { code: 'EC-F', name: 'Cañar', capital: 'Azogues', country: 'EC' },
  { code: 'EC-C', name: 'Carchi', capital: 'Tulcán', country: 'EC' },
  { code: 'EC-H', name: 'Chimborazo', capital: 'Riobamba', country: 'EC' },
  { code: 'EC-X', name: 'Cotopaxi', capital: 'Latacunga', country: 'EC' },
  { code: 'EC-O', name: 'El Oro', capital: 'Machala', country: 'EC' },
  { code: 'EC-E', name: 'Esmeraldas', capital: 'Esmeraldas', country: 'EC' },
  { code: 'EC-W', name: 'Galápagos', capital: 'Puerto Baquerizo Moreno', country: 'EC' },
  { code: 'EC-G', name: 'Guayas', capital: 'Guayaquil', country: 'EC' },
  { code: 'EC-I', name: 'Imbabura', capital: 'Ibarra', country: 'EC' },
  { code: 'EC-L', name: 'Loja', capital: 'Loja', country: 'EC' },
  { code: 'EC-R', name: 'Los Ríos', capital: 'Babahoyo', country: 'EC' },
  { code: 'EC-M', name: 'Manabí', capital: 'Portoviejo', country: 'EC' },
  { code: 'EC-S', name: 'Morona Santiago', capital: 'Macas', country: 'EC' },
  { code: 'EC-N', name: 'Napo', capital: 'Tena', country: 'EC' },
  { code: 'EC-D', name: 'Orellana', capital: 'Puerto Francisco de Orellana', country: 'EC' },
  { code: 'EC-Y', name: 'Pastaza', capital: 'Puyo', country: 'EC' },
  { code: 'EC-P', name: 'Pichincha', capital: 'Quito', country: 'EC' },
  { code: 'EC-SE', name: 'Santa Elena', capital: 'Santa Elena', country: 'EC' },
  { code: 'EC-SD', name: 'Santo Domingo de los Tsáchilas', capital: 'Santo Domingo', country: 'EC' },
  { code: 'EC-U', name: 'Sucumbíos', capital: 'Nueva Loja', country: 'EC' },
  { code: 'EC-T', name: 'Tungurahua', capital: 'Ambato', country: 'EC' },
  { code: 'EC-Z', name: 'Zamora Chinchipe', capital: 'Zamora', country: 'EC' },
];

export const EC_CITIES: readonly City[] = [
  { code: 'EC-CUE', name: 'Cuenca', subdivisionCode: 'EC-A', country: 'EC', isCapital: true },
  { code: 'EC-GIR', name: 'Girón', subdivisionCode: 'EC-A', country: 'EC' },
  { code: 'EC-GUA', name: 'Gualaceo', subdivisionCode: 'EC-A', country: 'EC' },
  { code: 'EC-PAU', name: 'Paute', subdivisionCode: 'EC-A', country: 'EC' },
  { code: 'EC-GRD', name: 'Guaranda', subdivisionCode: 'EC-B', country: 'EC', isCapital: true },
  { code: 'EC-CHI', name: 'Chillanes', subdivisionCode: 'EC-B', country: 'EC' },
  { code: 'EC-AZO', name: 'Azogues', subdivisionCode: 'EC-F', country: 'EC', isCapital: true },
  { code: 'EC-TRN', name: 'La Troncal', subdivisionCode: 'EC-F', country: 'EC' },
  { code: 'EC-TUL', name: 'Tulcán', subdivisionCode: 'EC-C', country: 'EC', isCapital: true },
  { code: 'EC-SGA', name: 'San Gabriel', subdivisionCode: 'EC-C', country: 'EC' },
  { code: 'EC-RIO', name: 'Riobamba', subdivisionCode: 'EC-H', country: 'EC', isCapital: true },
  { code: 'EC-ALU', name: 'Alausí', subdivisionCode: 'EC-H', country: 'EC' },
  { code: 'EC-GNO', name: 'Guano', subdivisionCode: 'EC-H', country: 'EC' },
  { code: 'EC-LAT', name: 'Latacunga', subdivisionCode: 'EC-X', country: 'EC', isCapital: true },
  { code: 'EC-SAQ', name: 'Saquisilí', subdivisionCode: 'EC-X', country: 'EC' },
  { code: 'EC-PUJ', name: 'Pujilí', subdivisionCode: 'EC-X', country: 'EC' },
  { code: 'EC-LMN', name: 'La Maná', subdivisionCode: 'EC-X', country: 'EC' },
  { code: 'EC-MAC', name: 'Machala', subdivisionCode: 'EC-O', country: 'EC', isCapital: true },
  { code: 'EC-PSJ', name: 'Pasaje', subdivisionCode: 'EC-O', country: 'EC' },
  { code: 'EC-SRO', name: 'Santa Rosa', subdivisionCode: 'EC-O', country: 'EC' },
  { code: 'EC-HUQ', name: 'Huaquillas', subdivisionCode: 'EC-O', country: 'EC' },
  { code: 'EC-ESM', name: 'Esmeraldas', subdivisionCode: 'EC-E', country: 'EC', isCapital: true },
  { code: 'EC-ATM', name: 'Atacames', subdivisionCode: 'EC-E', country: 'EC' },
  { code: 'EC-QND', name: 'Quinindé', subdivisionCode: 'EC-E', country: 'EC' },
  { code: 'EC-PBM', name: 'Puerto Baquerizo Moreno', subdivisionCode: 'EC-W', country: 'EC', isCapital: true },
  { code: 'EC-PAY', name: 'Puerto Ayora', subdivisionCode: 'EC-W', country: 'EC' },
  { code: 'EC-GYE', name: 'Guayaquil', subdivisionCode: 'EC-G', country: 'EC', isCapital: true },
  { code: 'EC-DUR', name: 'Durán', subdivisionCode: 'EC-G', country: 'EC' },
  { code: 'EC-SAM', name: 'Samborondón', subdivisionCode: 'EC-G', country: 'EC' },
  { code: 'EC-DAU', name: 'Daule', subdivisionCode: 'EC-G', country: 'EC' },
  { code: 'EC-MIL', name: 'Milagro', subdivisionCode: 'EC-G', country: 'EC' },
  { code: 'EC-NAR', name: 'Naranjal', subdivisionCode: 'EC-G', country: 'EC' },
  { code: 'EC-PLY', name: 'Playas', subdivisionCode: 'EC-G', country: 'EC' },
  { code: 'EC-ETR', name: 'El Triunfo', subdivisionCode: 'EC-G', country: 'EC' },
  { code: 'EC-IBA', name: 'Ibarra', subdivisionCode: 'EC-I', country: 'EC', isCapital: true },
  { code: 'EC-OTA', name: 'Otavalo', subdivisionCode: 'EC-I', country: 'EC' },
  { code: 'EC-COT', name: 'Cotacachi', subdivisionCode: 'EC-I', country: 'EC' },
  { code: 'EC-LOJ', name: 'Loja', subdivisionCode: 'EC-L', country: 'EC', isCapital: true },
  { code: 'EC-CTM', name: 'Catamayo', subdivisionCode: 'EC-L', country: 'EC' },
  { code: 'EC-MCR', name: 'Macará', subdivisionCode: 'EC-L', country: 'EC' },
  { code: 'EC-BAB', name: 'Babahoyo', subdivisionCode: 'EC-R', country: 'EC', isCapital: true },
  { code: 'EC-QVD', name: 'Quevedo', subdivisionCode: 'EC-R', country: 'EC' },
  { code: 'EC-VNC', name: 'Vinces', subdivisionCode: 'EC-R', country: 'EC' },
  { code: 'EC-VNT', name: 'Ventanas', subdivisionCode: 'EC-R', country: 'EC' },
  { code: 'EC-POR', name: 'Portoviejo', subdivisionCode: 'EC-M', country: 'EC', isCapital: true },
  { code: 'EC-MNT', name: 'Manta', subdivisionCode: 'EC-M', country: 'EC' },
  { code: 'EC-CHN', name: 'Chone', subdivisionCode: 'EC-M', country: 'EC' },
  { code: 'EC-JIP', name: 'Jipijapa', subdivisionCode: 'EC-M', country: 'EC' },
  { code: 'EC-PDR', name: 'Pedernales', subdivisionCode: 'EC-M', country: 'EC' },
  { code: 'EC-MCS', name: 'Macas', subdivisionCode: 'EC-S', country: 'EC', isCapital: true },
  { code: 'EC-SUC', name: 'Sucúa', subdivisionCode: 'EC-S', country: 'EC' },
  { code: 'EC-TEN', name: 'Tena', subdivisionCode: 'EC-N', country: 'EC', isCapital: true },
  { code: 'EC-ARC', name: 'Archidona', subdivisionCode: 'EC-N', country: 'EC' },
  { code: 'EC-FCO', name: 'Puerto Francisco de Orellana', subdivisionCode: 'EC-D', country: 'EC', isCapital: true },
  { code: 'EC-JYS', name: 'Joya de los Sachas', subdivisionCode: 'EC-D', country: 'EC' },
  { code: 'EC-PUY', name: 'Puyo', subdivisionCode: 'EC-Y', country: 'EC', isCapital: true },
  { code: 'EC-UIO', name: 'Quito', subdivisionCode: 'EC-P', country: 'EC', isCapital: true },
  { code: 'EC-SGQ', name: 'Sangolquí', subdivisionCode: 'EC-P', country: 'EC' },
  { code: 'EC-CYB', name: 'Cayambe', subdivisionCode: 'EC-P', country: 'EC' },
  { code: 'EC-MCH', name: 'Machachi', subdivisionCode: 'EC-P', country: 'EC' },
  { code: 'EC-SEL', name: 'Santa Elena', subdivisionCode: 'EC-SE', country: 'EC', isCapital: true },
  { code: 'EC-SAL', name: 'Salinas', subdivisionCode: 'EC-SE', country: 'EC' },
  { code: 'EC-LIB', name: 'La Libertad', subdivisionCode: 'EC-SE', country: 'EC' },
  { code: 'EC-SDO', name: 'Santo Domingo', subdivisionCode: 'EC-SD', country: 'EC', isCapital: true },
  { code: 'EC-NLJ', name: 'Nueva Loja', subdivisionCode: 'EC-U', country: 'EC', isCapital: true },
  { code: 'EC-SHU', name: 'Shushufindi', subdivisionCode: 'EC-U', country: 'EC' },
  { code: 'EC-AMB', name: 'Ambato', subdivisionCode: 'EC-T', country: 'EC', isCapital: true },
  { code: 'EC-BAN', name: 'Baños de Agua Santa', subdivisionCode: 'EC-T', country: 'EC' },
  { code: 'EC-PEL', name: 'Pelileo', subdivisionCode: 'EC-T', country: 'EC' },
  { code: 'EC-ZAM', name: 'Zamora', subdivisionCode: 'EC-Z', country: 'EC', isCapital: true },
  { code: 'EC-YNZ', name: 'Yantzaza', subdivisionCode: 'EC-Z', country: 'EC' },
];
