-- =============================================================================
-- KARGAX INTELLIGENCE — DATA LAYER MIGRATION
-- Fase 1: Nuevas columnas, índices y estructura para Intelligence Engine
-- =============================================================================

BEGIN;

-- 1. Nuevas columnas en cargo_offers para cancelaciones estructuradas y distancia estimada
ALTER TABLE public.cargo_offers
    ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS cancelled_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS cancellation_reason TEXT
        CHECK (cancellation_reason IS NULL OR cancellation_reason IN (
            'no_driver_available',
            'client_request',
            'pricing_issue',
            'cargo_not_ready',
            'weather_conditions',
            'vehicle_breakdown',
            'documentation_issue',
            'duplicate',
            'other'
        )),
    ADD COLUMN IF NOT EXISTS estimated_distance_km DECIMAL(10,2);

COMMENT ON COLUMN public.cargo_offers.cancelled_at IS
    'Timestamp of cancellation. Populated by application layer when status transitions to cancelled.';
COMMENT ON COLUMN public.cargo_offers.cancelled_by IS
    'User ID of the operator or client who performed the cancellation.';
COMMENT ON COLUMN public.cargo_offers.cancellation_reason IS
    'Structured reason for cancellation. Used by Intelligence Rules Engine for pattern detection.';
COMMENT ON COLUMN public.cargo_offers.estimated_distance_km IS
    'Haversine straight-line distance in km between origin and destination coordinates. Computed by application layer on offer creation/update.';

-- 2. Índices optimizados para consultas del motor de Inteligencia
CREATE INDEX IF NOT EXISTS idx_offers_intelligence_business_month
    ON public.cargo_offers(business_id, created_at DESC, status);

CREATE INDEX IF NOT EXISTS idx_offers_intelligence_trucker_status
    ON public.cargo_offers(assigned_trucker_id, status, delivery_verified_at DESC)
    WHERE assigned_trucker_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_offers_intelligence_route_cost
    ON public.cargo_offers(origin_city, destination_city, total_amount)
    WHERE status IN ('completed', 'in_progress');

CREATE INDEX IF NOT EXISTS idx_offers_intelligence_cancelled
    ON public.cargo_offers(business_id, cancelled_at DESC, cancellation_reason)
    WHERE status = 'cancelled';

CREATE INDEX IF NOT EXISTS idx_trucker_profiles_intelligence_license
    ON public.trucker_profiles(user_id, license_expiry, rating)
    WHERE is_verified = true;

CREATE INDEX IF NOT EXISTS idx_fuel_advances_intelligence_risk
    ON public.fuel_advances(trucker_id, status, due_at)
    WHERE status IN ('disbursed', 'overdue', 'at_risk');

-- 3. Documentación y soporte para alertas de Inteligencia
COMMENT ON TABLE public.algorithm_alerts IS
    'Executive operational alerts generated by read-only algorithms. Includes KargaX Intelligence rules engine alerts.';

COMMIT;
